package shared

data class Point4D(val x: Int, val y: Int, val z: Int, val w: Int) {
    val adjacents by lazy { listOf(
        Point4D(x+1, y, z, w),
        Point4D(x+1, y, z, w + 1),
        Point4D(x+1, y, z, w - 1),
        Point4D(x-1, y, z, w),
        Point4D(x-1, y, z, w + 1),
        Point4D(x-1, y, z, w - 1),
        Point4D(x+1, y+1, z, w),
        Point4D(x+1, y+1, z, w + 1),
        Point4D(x+1, y+1, z, w - 1),
        Point4D(x-1, y+1, z, w),
        Point4D(x-1, y+1, z, w + 1),
        Point4D(x-1, y+1, z, w - 1),
        Point4D(x+1, y-1, z, w),
        Point4D(x+1, y-1, z, w + 1),
        Point4D(x+1, y-1, z, w - 1),
        Point4D(x-1, y-1, z, w),
        Point4D(x-1, y-1, z, w + 1),
        Point4D(x-1, y-1, z, w - 1),
        Point4D(x, y+1, z, w),
        Point4D(x, y+1, z, w + 1),
        Point4D(x, y+1, z, w - 1),
        Point4D(x, y-1, z, w),
        Point4D(x, y-1, z, w + 1),
        Point4D(x, y-1, z, w - 1),
        Point4D(x+1, y, z + 1, w),
        Point4D(x+1, y, z + 1, w + 1),
        Point4D(x+1, y, z + 1, w - 1),
        Point4D(x-1, y, z + 1, w),
        Point4D(x-1, y, z + 1, w + 1),
        Point4D(x-1, y, z + 1, w - 1),
        Point4D(x+1, y+1, z + 1, w),
        Point4D(x+1, y+1, z + 1, w + 1),
        Point4D(x+1, y+1, z + 1, w - 1),
        Point4D(x-1, y+1, z + 1, w),
        Point4D(x-1, y+1, z + 1, w + 1),
        Point4D(x-1, y+1, z + 1, w - 1),
        Point4D(x+1, y-1, z + 1, w),
        Point4D(x+1, y-1, z + 1, w + 1),
        Point4D(x+1, y-1, z + 1, w - 1),
        Point4D(x-1, y-1, z + 1, w),
        Point4D(x-1, y-1, z + 1, w + 1),
        Point4D(x-1, y-1, z + 1, w - 1),
        Point4D(x, y+1, z + 1, w),
        Point4D(x, y+1, z + 1, w + 1),
        Point4D(x, y+1, z + 1, w - 1),
        Point4D(x, y-1, z + 1, w),
        Point4D(x, y-1, z + 1, w + 1),
        Point4D(x, y-1, z + 1, w - 1),
        Point4D(x, y, z + 1, w),
        Point4D(x, y, z + 1, w + 1),
        Point4D(x, y, z + 1, w - 1),
        Point4D(x+1, y, z - 1, w),
        Point4D(x+1, y, z - 1, w + 1),
        Point4D(x+1, y, z - 1, w - 1),
        Point4D(x-1, y, z - 1, w),
        Point4D(x-1, y, z - 1, w + 1),
        Point4D(x-1, y, z - 1, w - 1),
        Point4D(x+1, y+1, z - 1, w),
        Point4D(x+1, y+1, z - 1, w + 1),
        Point4D(x+1, y+1, z - 1, w - 1),
        Point4D(x-1, y+1, z - 1, w),
        Point4D(x-1, y+1, z - 1, w + 1),
        Point4D(x-1, y+1, z - 1, w - 1),
        Point4D(x+1, y-1, z - 1, w),
        Point4D(x+1, y-1, z - 1, w + 1),
        Point4D(x+1, y-1, z - 1, w - 1),
        Point4D(x-1, y-1, z - 1, w),
        Point4D(x-1, y-1, z - 1, w + 1),
        Point4D(x-1, y-1, z - 1, w - 1),
        Point4D(x, y+1, z - 1, w),
        Point4D(x, y+1, z - 1, w + 1),
        Point4D(x, y+1, z - 1, w - 1),
        Point4D(x, y-1, z - 1, w),
        Point4D(x, y-1, z - 1, w + 1),
        Point4D(x, y-1, z - 1, w - 1),
        Point4D(x, y, z - 1, w),
        Point4D(x, y, z - 1, w + 1),
        Point4D(x, y, z - 1, w - 1),
        Point4D(x, y, z, w + 1),
        Point4D(x, y, z, w - 1)
    ) }
}